[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Copyright &copy; 2024 King of Gores Community'
    alertText = ''

[ru]
  languageName = "Русский"
  contentDir = "content/ru"
  weight = 10
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
    footer = 'Авторское право &copy; 2024 сообщество King of Gores'
    alertText = ''

[tr]
  languageName = "Türkçe"
  contentDir = "content/tr"
  weight = 10
  [tr.params]
    languageISO = "TR"
    languageTag = "tr-TR"
    footer = 'King of Gores Topluluğu &copy; 2024 - Tüm hakları saklıdır'
    alertText = ''
